services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    image: omakase-rooms-go-backend:multistage
    container_name: omakase-rooms-go-backend-multistage
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
