services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: omakase-rooms-go-backend
    container_name: omakase-rooms-go-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
