apiVersion: apps/v1
kind: Deployment
metadata:
  name: omakase-rooms-go-backend-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omakase-rooms-go-backend
  template:
    metadata:
      labels:
        app: omakase-rooms-go-backend
    spec:
      containers:
        - name: omakase-rooms-go-backend-app
          image: europe-west3-docker.pkg.dev/omakase-rooms-go-backend-gcp/omakase-rooms-go-backend-repo/omakase-rooms-go-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
