apiVersion: "v1"
kind: "Service"
metadata:
  name: "omakase-rooms-go-backend-gke-service"
  namespace: "default"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: "omakase-rooms-go-backend"
  type: "LoadBalancer"
  loadBalancerIP: ""
